ALTER TABLE "PaperInfo"
ADD COLUMN "ci_file_size" TEXT DEFAULT '',
ADD COLUMN "ci_updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "ci_updated_by" TEXT DEFAULT '',
ADD COLUMN "insert_file_size" TEXT DEFAULT '',
ADD COLUMN "insert_updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "insert_updated_by" TEXT DEFAULT '',
ADD COLUMN "ms_file_size" TEXT DEFAULT '',
ADD COLUMN "ms_updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "ms_updated_by" TEXT DEFAULT '',
ADD COLUMN "qp_file_size" TEXT DEFAULT '',
ADD COLUMN "qp_updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "qp_updated_by" TEXT DEFAULT '';
